// Compatibility barrel. New code should import types from the owning domain.
export type { AnkiCardInput, AnkiSettings, AnkiStatus } from "./anki/types";
export type {
  AudioDevice,
  AudioLevel,
  AudioOutputSettings,
  LiveTranscription,
  MicrophoneSettings,
  VadSettings,
} from "./capture/types";
export type {
  ChatboxComposeInput,
  ChatboxMessage,
  ChatboxMessageFormat,
  ChatboxOverflowPolicy,
  ChatboxPreview,
  ChatboxSendMode,
} from "./chatbox/types";
export type {
  ActiveLanguageSession,
  ConnectionState,
  Health,
  LanguageSessionSnapshot,
} from "./core-client/types";
export type {
  DictionaryEntry,
  DictionaryImportProgress,
  DictionarySource,
} from "./dictionary/types";
export type {
  ExternalApiRuntimeStatus,
  ExternalApiSettings,
  OscRuntimeStatus,
  VrchatMuteStatus,
  VrOverlayContentMode,
  VrOverlayControllerHand,
  VrOverlayHand,
  VrOverlayHeadsetSettings,
  VrOverlayResourceState,
  VrOverlayResourceStatus,
  VrOverlayRuntimeState,
  VrOverlaySettings,
  VrOverlayStatus,
  VrOverlayTranslationDisplay,
  VrOverlayWristSettings,
  VrOverlayWristStatus,
  VrcxRuntimeStatus,
  VrcxSettings,
} from "./integrations/types";
export type {
  LearningAnalysis,
  LearningAnalysisConfidence,
  LearningAnalysisFocus,
  LearningAnalysisInput,
  LearningAnalysisSegment,
  LearningCardDraft,
  LearningCardType,
  LearningDraftInput,
  LearningExample,
  LearningGrammarPoint,
  LearningItem,
  LearningItemCreateInput,
  LearningItemKind,
  LearningItemPatchInput,
  LearningItemStatus,
  LearningLevel,
  LearningTaskType,
  SelectionQueryInput,
  SelectionQueryResponse,
} from "./learning/types";
export type {
  ApiAuthMode,
  ApiCapability,
  ApiModelCatalog,
  ApiProfile,
  ApiProfileInput,
  ApiProfileView,
  ApiProvider,
  AsrCapabilities,
  AsrModelCapability,
  AsrModelRecord,
  AsrModelStatus,
  AsrSettings,
  ConnectionDiagnostic,
  ConnectionDiagnosticCheck,
  HttpHeaderConfig,
  ProviderCapabilities,
  ProviderCategory,
  ProviderConnectionDefinition,
  ProviderConnectionField,
  ProviderDefinition,
  ProviderPreset,
  ProviderServiceDefinition,
  ProviderSupportLevel,
  ProviderSupportLevels,
  RecognitionServiceSettings,
  RecognitionTransport,
} from "./providers/types";
export type { CredentialStatus } from "./shared/protocol/credentials";
export type {
  GlossaryCategory,
  GlossaryEntry,
  GlossaryLocalSource,
  GlossarySettings,
  GlossarySource,
  GlossarySourceStatus,
  GlossarySubscriptionSource,
  LanguagePreset,
  OscTranslationStrategy,
  Settings,
  TranslationPromptPreview,
  TranslationPromptSettings,
  TranslationSettings,
  TranslationTargetSettings,
} from "./settings/types";
export type { DatabaseStorageStats } from "./storage/types";
export type {
  Subtitle,
  SubtitleTranslation,
  TranslationEvent,
} from "./subtitles/types";
